name: appteste
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  flutter_auth_buttons: ^0.6.0
  meta: ^1.1.8
  auto_size_text: ^2.1.0





  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.1.1



flutter:

 
  uses-material-design: true
  assets:
    - assets/images/
